"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var advertisementController_1 = require("./advertisementController");
var router = (0, express_1.Router)();
router.get('/backstagegear', advertisementController_1.getAds);
router.get('/backstagegear/ads', advertisementController_1.getAds);
router.get('/backstagegear/ads/:adId', advertisementController_1.getAdDatasById);
router.get('/backstagegear/:userName/ads', advertisementController_1.getUserAds);
router.get('/backstagegear/:userName/ads/:adId', advertisementController_1.getUserAdById);
exports.default = router;
