"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = __importDefault(require("express"));
var cors_1 = __importDefault(require("cors"));
var body_parser_1 = __importDefault(require("body-parser"));
var routes_1 = __importDefault(require("../category/routes"));
var routes_2 = __importDefault(require("../advertisement/routes"));
var routes_3 = __importDefault(require("../profile/routes"));
var routes_4 = __importDefault(require("../message/routes"));
var app = (0, express_1.default)();
app.use((0, cors_1.default)({ origin: "*" }));
app.use(body_parser_1.default.json());
app.use(body_parser_1.default.urlencoded({ extended: true }));
app.use(express_1.default.json());
app.use('/', routes_1.default);
app.use('/', routes_2.default);
app.use('/', routes_3.default);
app.use('/', routes_4.default);
exports.default = app;
